<?php 
class details 
{
    private $name , $mobile;
    private function show($n , $mo)
    {
        $this->name = $n;
        $this->mobile = $mo;
    }
    function __call($method , $args){
        if(method_exists($this , $method)) {
            call_user_func_array([$this , $method] , $args);    // private method ni value set kara mate 
        } else {       
            echo "This error msg is generated by $method" . "<br>";
            echo "<pre>";
            print_r($args);
        }
    }
}

$obb = new details();
$obb->show("Dhenish" , 143);
// $obb->display(); // non execiting method error by __call() method 
echo "<pre>";
print_r($obb);
$obb->ohj();
?>